Pseudocodigo
andrea-carmona/bizboost pull request #1
Opened 2023-07-12 22:37 UTC by andrea-carmona

Hello Architect:

 completion of the pseudocode.

Thanks so much

2023-07-12 23:17 UTC, jorgecarmona requested changes
Checar comentarios y corregir

2023-07-12 23:17 UTC, jorgecarmona commented on src/index.html
> +    - 3 boxes de flexbox "imagen and article"
en lugar de article deberia de ser un <p> porque un article es mas que un caption debajo de una imagen.

2023-07-12 23:17 UTC, jorgecarmona commented on src/index.html
> +      -h3,
y la imagen?

2023-07-12 23:17 UTC, jorgecarmona commented on src/index.html
> +      -h6 "subtitulo"
lo veo del mismo tamano del h5

2023-07-12 23:17 UTC, jorgecarmona commented on src/index.html
> +    -<mark "HOME"
el `home` es un menu que esta azul porque esta seleccionado

2023-07-12 23:17 UTC, jorgecarmona commented on src/index.html
> +      - Flex box "redes sociales "  -->
y el copyright?

2023-07-13 00:01 UTC, andrea-carmona commented
Ya realice los cambios:

2023-07-13 00:08 UTC, andrea-carmona commented on src/index.html
> +      -h3,
Ya quedo el cambio y vamos a usar figure

2023-07-13 00:08 UTC, andrea-carmona commented on src/index.html
> +      -h6 "subtitulo"
done

2023-07-13 00:09 UTC, andrea-carmona commented on src/index.html
> +    -<mark "HOME"
done

2023-07-13 00:09 UTC, andrea-carmona commented on src/index.html
> +      - Flex box "redes sociales "  -->
done

2023-07-13 00:11 UTC, jorgecarmona approved these changes
Aprobado para empezar

2023-07-13 00:13 UTC, merged